---
all:
  children:
    vpn_servers:
      hosts:
        vpn-main-1:
          ansible_host: CHANGE_ME
          ansible_user: root
          ansible_port: 22
          vpn_server_role: main
          vpn_public_endpoint: CHANGE_ME
        vpn-reserve-1:
          ansible_host: CHANGE_ME
          ansible_user: root
          ansible_port: 22
          vpn_server_role: reserve
          vpn_public_endpoint: CHANGE_ME

