---
- name: Install VPN alert rules
  ansible.builtin.template:
    src: vpn-alert-rules.yml.j2
    dest: /etc/prometheus/rules/vpn-alert-rules.yml
    owner: root
    group: root
    mode: "0644"
  notify: Restart prometheus
